DROP TABLE IF EXISTS login_users;  
CREATE TABLE login_users (  
UserId INTEGER AUTO_INCREMENT  PRIMARY KEY,  
username VARCHAR(50) NOT NULL,  
password VARCHAR(100) NOT NULL,  
email VARCHAR(100) NOT NULL, 
phone_no INTEGER NOT NULL, 
Address VARCHAR(150) NOT NULL, 
zipcode VARCHAR(10) NOT NULL
);  